import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login');
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('Admin');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('admin123');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('link', { name: 'PIM' }).click();
  await page.getByRole('link', { name: 'Add Employee' }).click();
  await page.getByRole('textbox', { name: 'First Name' }).click();
  await page.getByRole('textbox', { name: 'First Name' }).fill('pvan');
  await page.getByRole('textbox', { name: 'First Name' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'First Name' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'First Name' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'First Name' }).fill('pavan');
  await page.getByRole('textbox', { name: 'First Name' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'First Name' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'First Name' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'First Name' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Last Name' }).click();
  await page.getByRole('textbox', { name: 'Last Name' }).fill('kumar');
  await page.getByRole('textbox').nth(4).click();
  await page.getByRole('textbox').nth(4).fill('0000123');
  await page.locator('.oxd-switch-input').click();
  await page.getByRole('textbox').nth(5).click();
  await page.getByRole('textbox').nth(5).fill('Pavan');
  await page.locator('input[type="password"]').first().click();
  await page.locator('input[type="password"]').first().fill('pavan123');
  await page.locator('input[type="password"]').nth(1).click();
  await page.locator('input[type="password"]').nth(1).fill('pavan123');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.goto('https://opensource-demo.orangehrmlive.com/web/index.php/pim/viewPersonalDetails/empNumber/193');
  await expect(page.getByRole('heading', { name: 'Personal Details' })).toBeVisible();
});